baseurl = "https://spsufawi.netlify.com/"
publishDir = "docs"
title = "Hugo Tanka Theme"
author = "Nan Xiao"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "R · Data Scince · sample(thoughts, 1)"

[[menu.main]]
    name = "Home"
    url = "https://spsufawi.netlify.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/spsufawi"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/xinchenpan"
    weight = 3
