baseurl = "https://spsufawi.rbind.io/"
publishDir = "docs"
title = "Xinchen's Blog"
author = "Xinchen Pan"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
googleAnalytics = "UA-119879446-1"
disqusShortname = "https-spsufawi-netlify-com"
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "R · Data Scince · sample(thoughts, ?)"
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/spsufawi"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about"