---
title: 看书
author: Xinchen Pan
date: '2018-05-10'
slug: reading
categories:
  - Thoughts
tags: []
---

新年的时候给今年做了个规划，大概就是要看多少书，完成多少门公开课之类的。我计划今年看四十本书，到现在确实看书这个目标是一直在做，目前正在看第十五本，但问题是我看的书种类太单一, 读完的书14本有13本是小说，3本村上春树的，7本东野圭吾的，1本余华的，1本石黑一雄的，1本川端康成的，还一本是《One hour bitcoin》，看到kindle广告推荐，就读了下。现在读的这本又是东野圭吾的。
为什么喜欢读东野圭吾的书，最大的原因就是容易看进去，东野圭吾小说基本都会很早就开始设置悬念，一直吸引你读到小说结束。东野到现在写了90多本小说，说实话我是都想读完的，按照现在这个进度差不多要两年，但我觉得读到书的种类应该多种多样，不能局限于一个题材，一个作者的书。虽说看书很重要的一个目的是消遣，是磨时间，但如果能看一些让你扩大视野，增长不同方面的见识的书也许会更好。还有一类书我称之为“硬书”，它的一个特点是全英文，领域多为心理学，社会学或经济学，作者是非常有名的人物，可能是大学教授，可能是诺贝尔奖获得者，我认为这类书读完会大有益处。为什么要看英文的，我觉得如果作者本身是用英文写作的话，原著会更原汁原味点。这又造成了另一个问题，就是难读懂，自己的英文水平看看新闻，维基百科还可以，看原版本确实有不少不认识的单词，如果看的时候被一个词卡住而不懂句子意思会比较头疼，更多时候都懒得查字典，直接跳过去，最终造成内容理解不深，甚至完全不理解，直接忘记，它毕竟不是小说，脑子里不会出现画面。

看完这一本东野圭吾的《梦幻花》，就打算看看“硬书”了，同学推荐了一本《thinking fast and slow》，看了介绍觉得很不错。另外之前在Jordan Peterson那个视频比较火的时候，我也买了它的一本名字鸡汤为很浓的书，《twelve rules for life》，很惭愧的第一章都没看完。自己也对心理学非常感兴趣，尤其是共时性，解梦这块，但对心理学总体还知之甚少，也不知道从哪本书哪个作者入手读比较好，就知道几个比较有名的心理学家，荣格，佛洛依德等，估计会先读下他们的基本经典著作

还有就是一年看多少本书这个计划当然不是固定的，只是为了让自己养成一个多看书的习惯，现在这个习惯确实是养成了。总而言之不能为了看书而看书，看了之后能得到一些思考，写个读书笔记是最好的，自己也许是懒得写了。
