---
title: 青春大概
author: Xinchen Pan
date: '2018-05-18'
slug: youth
categories:
  - Thoughts
tags: []
---


<blockquote> 

在遗忘中不舍，醉醒交错， 青春大概如你所说。  
在花落时结果，期望很多，青春大概都这样过。  
</blockquote>

上周末回了一下学校参加硕士毕业典礼，和同学拍了几张毕业照，也算是正式和学生身份告别了。回到芝加哥这几天有点惆怅，开始听一些关于毕业季的校园歌曲。最早是听的《今年夏天》，从评论里看到有人提到《青春大概》，于是也搜来听听，第一遍就把我听哭了，在凌晨12点多。接着中毒一般两天听了不知道有没有100遍。后来在bilibili搜这首歌的时候又偶然发现复旦大学历年的毕业mv，通常这类视频我都没多大兴趣点进去，但这次我点进去了，把复旦15-17年的毕业mv都看了一遍，三首歌我都很喜欢，最喜欢的是15年的那首《那年那少年》，两天又听了无数遍，仿佛中毒一般，一遍一遍的听，最喜欢的都是最后男女合唱的部分。

我向来对有男女一起大合唱的歌没有抵抗力，觉得那是世界上最美好的声音之一。喜欢这两首歌一个原因是副歌的男女合唱很有感染力，另外就是它的毕业与青春属性。

我想这会是我最后一次提到我的本科那些事情，总是翻不过去那一页。

我的大学四年自然是充满无数悔恨和遗憾的，除了交了几个好朋友，我的本科几乎没有任何美好的回忆，以至于我都不想不想打开这篇有2000回答的问题
[你大学生活最美好的时刻是？](https://www.zhihu.com/question/46598176)

14年暑假回到学校第一件事就是写了一篇很长的总结，检讨我本科出的问题，现在已经记不起当时写的什么了，那就重新回想下。



1.	大一进入到学校就完全没有任何激动和自豪感，甚至感觉自己进入了一个不好的大学，这个想法现在看来当然是很愚蠢的，虽然UIUC的录取率很高，但其教育质量和提供的机会绝对是强于绝大部分国内的大学，即使学生的平均水平不如国内少部分大学。每年有很多从国内转过来的人，因为他们知道这边机会更多，在这边取得一个高GPA相对来说比国内要简单，申请研究生海本也更有优势，所以UIUC是一个好的选择，虽然前提还是你能保持一个好的成绩，这在哪都一样。可惜我当时没有这个觉悟，我想要有莫名其妙所谓的自豪感 – 在国内得是中山以上的大学，美国得是top30，讽刺的是我却没有为他们而拼搏过。而UIUC是出了名的中国学生多，当时普遍认为去中国留学生多的学校不好，于是自己带着一种对未来完全没有任何期许，对新生活没有任何期待的心情来到了美国，来到了玉米地。

2.	几乎没有的自制力和严重的拖延症。清楚的记得大一上学期在宿舍的时候，看着时间对自己说再逛半小时贴吧再学习，时间从7点半到了8点，哦，8点03了，不是整数了，8点半再开始写作业吧，就这么可以拖到10点。大一下成绩开始血崩是在drop了一门cs课之后，drop一门课这种再正常不过的事情不知道为什么会让自己觉得仿佛天塌下来了，drop这门课多出来的时间自己却开始堕落，就像高压结束之后的突然的泄气，于是疯狂放纵，明知不应该这样，却还是痛并快乐着的继续下去

3.	不方便透露的客观原因，有影响，但和上边两个原因比不值一提。

最大的是触动还是遗憾自己失去了最美好的大学年华，虽然我知道人生会有很多遗憾。

既然已经无法改变，那么我应该想想，现在应该做些什么，可以让以后的我不对现在26,27岁的我产生遗憾。

虽然不想，未来却还是可能有更大的困难，无论怎样都要勇敢面对。

自己写的东西鸡汤味越来越浓了。

