---
title: 自我
author: Xinchen Pan
date: '2018-06-13'
slug: self-consciousness
categories:
  - Thoughts
tags: []
---

最近看书看到了一个词，叫做self-consciousness, 维基百科上的解释是

<blockquote>It is a preoccupation with oneself, as opposed to the philosophical state of self-awareness, which is the awareness that one exists as an individual being, though the two terms are commonly used interchangeably or synonymously. 
</blockquote>
简单翻译过来就是自我意识 --- 这种意识有可能会让人产生不愉快的感觉

<blockquote>An unpleasant feeling of self-consciousness may occur when one realizes that one is being watched or observed, the feeling that "everyone is looking" at oneself. </blockquote>

这种不舒服的感觉说的就是自我意识过剩。

我认为自己就是个自我意识过剩的人，先说几个故事。

初一的时候语文老师布置了一篇作文，主题是介绍自己，然后在一节语文课上，语文老师分别展示了三个学生的作文，分别为A等级B等级C等级，我的作文是第三个被展示的，也就是C等级的那个。我清楚地记得投影仪清楚地显示出字迹那一刻自己是多么羞怯。虽然老师没有说作者是谁，但同学们纷纷朝我这边看表示他们很快知道这是我写的。我的作文具体是哪里有问题我早已记不清了，只记得我写的一段话被同学嘲笑了，我大概写的是“我很喜欢听音乐，喜欢的歌手有刘德华”，德字写错了。下课在走廊休息的时候，几个同学问我“刘德助”是谁，“刘德修”是谁，现在想想有点奇怪因为我华字不至于写错，也许记忆出现了偏差，但总体而言这件事对我造成了不小的影响。

初二又是一节语文课，还是关于作文的，我在期中考试的作文里写了一个“蠢”字，但是这个字写错了，漏了一个“日”，老师在黑板上写完这个字后说了句“蠢不蠢啊”，当然这次同学们不知道是我写的，却还是对自己的自尊心造成了打击。

初二劳技课，因为我坐在最边上，老师给我钥匙让我去楼下某个教室拿教材，可能是没听清是哪个教室，那个门我怎么也打不开。回到教室门口报告给老师，他说你是不是开错门了，我用傻笑缓解自己的尴尬，同学们一阵哄笑。

在我成长过程中，我妈说过我好多次“动手能力太差了”，“哪像做事的人”，这几句话对我造成的影响一直到现在还存在，我依旧认为自己在动手能力上比别人差。

这些事加在一起导致了我性格内向，在很多人前做事会紧张的性格，下面是几个例子。

大一刚来美国的时候买了一辆自行车，美国这边自行车一般都挂在公交车的车头的自行车架，当时我把自行车架拉下来，把车子放上去，上车之后司机和我说“你自行车掉了我可不负责”，一听到这句话我就开始紧张，觉得全车的人都在盯着自己。于是赶紧下车，把自行车掉了一个头，再上车，司机又说了句什么，没听懂，然后他很生气的一熄火下了车来，把固定自行车前轮的support arm拉上了，说了句“How hard is that？” 我一直不停的说sorry，我第一次用。上了车，又感觉到乘客的眼光，我盯着地板找了个座位坐下，心情自然不会好。

还是关于公交车的，美国公交车最前边的位置通常都有左右两排座位，如果有坐轮椅的上车，那两排座位需要收起来放上去，给轮椅腾出空间。具体如何操作我也不是很清楚，只是假如我坐在那个位置上，需要我去做这件事，在很多人的注视下，可能会摸索很久。最怕的是什么，是摁了某个按钮之后，椅子还是收不上。

同样的事情还有，在日本的新干线列车上，座位是可以前后转动的，由于我们需要把箱子放在座位中间，需要把两排对着的座位的其中一排转到另一个方向，由于我手里有两个箱子，另外一个乘客很麻利的在座位底下摆弄了一下，一转动，三座位的座位就转了方向。
如果我去做这件事呢。

这些事情真的难吗，我想不可能难，那为什么我担心自己不能像被人一样做到，我认为源头还是害怕别人的眼光，在众人的注视下，我希望自己能快速完成，这种紧张着急的心态会让自己慌张。

再仔细想想，人们真的会注意你吗，很多人也许只是看你一眼就继续看窗外或者手机了，再退一步，假设你弄了半天没弄好，人们真的会笑你吗，不会吧。

由于自己是上边所说的那种人，如果我看到别人这样(自行车放了半天放不上去，甚至更囧的事)，我完全不会有任何感觉。


网上搜了下关于self-consicousness的文章，有个实验引起了我的兴趣

<blockquote>In an experiment published in 2000, the psychologist Thomas Gilovich and his colleagues asked undergraduates to wear a piece of clothing that they found embarrassing—a t-shirt with a picture of singer-songwriter Barry Manilow on it. After putting on the shirt, the undergraduates had to spend some time in a room with other students and were later asked to guess how many of the other students noticed what they were wearing. The undergraduates tended to overestimate the proportion by a large margin, and did the same when asked to wear a t-shirt with a positive image on it, like Bob Marley or Martin Luther King Jr. In study after study, experimental subjects thought that other people would notice them much more than they actually did.
</blockquote>

我大二买过一件衣服，衣服上写着“fate loves the fearless"，后来穿出去突然觉得这几个单词美国人看了会不会我很幼稚，人家是不是会在心里“哼”一下，“look at that guy" 

自己肯定是多虑了，从上边的实验来看，人们会过度估计别人注意自己的程度。

有的时候遇到类似公交车放自行车那种事我会和同学交流，来寻找安慰，试图让人理解。我想就算是第一次用，很多人也许扫一眼就明白该如何放了，不过我还确实找到了一个关于如何在车头放自行车的guide。

https://www.transitchicago.com/howto/bring-your-bike-bus/






